Fix Python3 compatibility
* AttributeError: 'module' object has no attribute 'urlencode'
  > Try importing python3 names, else use python2.7 names.
  > http://python-future.org/compatible_idioms.html#urllib-module

* TypeError: the JSON object must be str, not 'bytes'
  > Call .decode('utf-8') before passing response to json.loads()
  > https://stackoverflow.com/q/6862770/319266

* TypeError: 'dict_keys' object does not support indexing
  > Fixed by 2to3 by wrapping in list().